# Generated by Django 3.1.1 on 2020-09-16 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.FileField(default='user/user.png', upload_to=user.models.user_directory_path)),
                ('website_url', models.URLField(blank=True, default='https://mywebsite.com/')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/')),
                ('github_url', models.URLField(blank=True, default='https://github.com/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
